/**
 * core/faq-manager.ts
 * Rileva pattern ricorrenti negli eventi di errore e genera automaticamente FAQ.
 * Analizza gli eventi 'error_encountered' e 'task_failed' per identificare
 * pattern ripetuti e propone la creazione di knowledge entries di tipo FAQ.
 *
 * @module core/faq-manager
 */

import { getDatabase } from './database.js';
import { createKnowledgeEntry } from './db-knowledge.js';

// ---------------------------------------------------------------------------
// Tipi
// ---------------------------------------------------------------------------

/**
 * Candidato FAQ: pattern ricorrente negli eventi.
 */
export interface FaqCandidate {
  /** Il pattern ricorrente (es. "TS2353", "ERR_CONNECTION_REFUSED") */
  pattern: string;
  /** Quante volte è apparso */
  occurrences: number;
  /** Titolo suggerito per la FAQ */
  suggestedTitle: string;
  /** Esempio più recente del pattern */
  recentExample: string;
}

// ---------------------------------------------------------------------------
// Rilevamento candidati FAQ
// ---------------------------------------------------------------------------

/**
 * Analizza gli eventi di tipo 'error_encountered' e 'task_failed' e trova
 * pattern ripetuti. Raggruppa per summary e conta le occorrenze.
 *
 * @param minOccurrences - Numero minimo di occorrenze per considerare un pattern (default: 3)
 * @returns Array di candidati FAQ ordinati per occorrenze decrescenti
 */
export function detectFaqCandidates(minOccurrences?: number): FaqCandidate[] {
  const db = getDatabase();
  const minOccur = minOccurrences ?? 3;

  // Verifica che la tabella events esista e abbia dati
  try {
    // Controllo preliminare: tabella events esiste?
    const tableCheck = db.prepare(
      "SELECT name FROM sqlite_master WHERE type='table' AND name='events'"
    ).get() as { name: string } | undefined;

    if (!tableCheck) {
      console.error('[faq-manager] events table not found');
      return [];
    }

    // Raggruppa eventi di errore per summary e conta occorrenze
    const rows = db.prepare(`
      SELECT
        summary,
        COUNT(*) as occurrences,
        MAX(timestamp) as recent_timestamp
      FROM events
      WHERE event_type IN ('error_encountered', 'task_failed')
      GROUP BY summary
      HAVING occurrences >= ?
      ORDER BY occurrences DESC
    `).all(minOccur) as Record<string, unknown>[];

    return rows.map(row => {
      const summary = String(row.summary ?? '');
      const occurrences = Number(row.occurrences ?? 0);
      const recentTimestamp = String(row.recent_timestamp ?? '');

      return {
        pattern: truncate(summary, 120),
        occurrences,
        suggestedTitle: generateFaqTitle(summary),
        recentExample: formatExample(summary, recentTimestamp),
      };
    });
  } catch (err) {
    console.error('[faq-manager] Error detecting FAQ candidates:', err instanceof Error ? err.message : String(err));
    return [];
  }
}

// ---------------------------------------------------------------------------
// Generazione FAQ
// ---------------------------------------------------------------------------

/**
 * Genera una knowledge entry di tipo FAQ a partire da un candidato FAQ.
 * Crea una entry strutturata con pattern, occorrenze e spazio per soluzione.
 *
 * @param candidate - Candidato FAQ da trasformare in knowledge entry
 * @param agentName - Nome dell'agente che genera la FAQ
 */
export function generateFaqFromCandidate(candidate: FaqCandidate, agentName: string): void {
  const title = candidate.suggestedTitle;

  const body = [
    `## Problema\n\n${candidate.pattern}\n`,
    `## Occorrenze\n\nQuesto errore è apparso **${candidate.occurrences} volte**. `,
    `È stato rilevato automaticamente dal sistema di pattern recognition.\n`,
    `## Esempio recente\n\n\`\`\`\n${candidate.recentExample}\n\`\`\`\n`,
    `## Causa\n\n*Da documentare — analizza il contesto in cui si è verificato l'errore.*\n`,
    `## Soluzione\n\n*Da documentare — descrivi i passi per risolvere il problema.*\n`,
  ].join('\n');

  createKnowledgeEntry(
    title,
    body,
    'faq',
    agentName,
    ['autogenerated', 'faq', 'recurring-error'],
    undefined
  );
}

// ---------------------------------------------------------------------------
// Helper privati
// ---------------------------------------------------------------------------

/**
 * Tronca una stringa a una lunghezza massima aggiungendo "..." se necessario.
 */
function truncate(text: string, maxLength: number): string {
  if (text.length <= maxLength) return text;
  return text.substring(0, maxLength - 3) + '...';
}

/**
 * Genera un titolo per la FAQ basato sul summary dell'errore.
 */
function generateFaqTitle(summary: string): string {
  // Cerca di estrarre un identificativo significativo (codice errore, nome)
  const errorCodeMatch = summary.match(/([A-Z]+\d+(?:-\d+)?|[A-Z_]+(?:\s+\d+)?)(?:\s|:|$)/);
  const prefix = 'FAQ: ';

  if (errorCodeMatch) {
    const code = errorCodeMatch[1].trim();
    return `${prefix}${code} — ${truncate(summary.replace(code, '').replace(/[:;]\s*/, '').trim(), 80)}`;
  }

  return `${prefix}${truncate(summary, 100)}`;
}

/**
 * Formatta un esempio per la FAQ includendo timestamp.
 */
function formatExample(summary: string, timestamp: string): string {
  const ts = timestamp ? `[${timestamp}] ` : '';
  return `${ts}${summary}`;
}
